name: demo

services:
  keycloak:
    container_name: keycloak
    hostname: keycloak.internal.test
    ports:
        - "443:443"
    environment:
        - KC_BOOTSTRAP_ADMIN_USERNAME=admin
        - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    image: quay.io/keycloak/keycloak:26.0
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf
      - ./certs:/certs
    command: start
  
  app:
    container_name: app
    build: .
    ports:
      - "5000:5000"

volumes:
  keycloak_data:
